version: "3.9"

services:
  postgresql:
    restart: always
    image: 'postgres:latest'
    container_name: user_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=user
    ports:
      - '5432:5432'
